### ISSUE TITLE
Uncaught Error: Call to a member function get() on null

### ISSUE THREAD

**Issue by kamalahmed** [piklist/piklist#124]
### Details
If I run any WP_Query after declaring support for piklist plugin in the plugin header && pklist is active, I get a fatal error. I can not run the following query anywhere in my plugin file.
If I the piklist plugin is deactivated, then the following query works fine. I needed this query to build an option in redux option page. I tested this code in the redux's config.php and as well as in my plugin main file, everywhere it fails if Piklist plugin is active. However, if I run this code inside the init hook or inside any metabox related file provided by piklist, then no error happens. 

So, I am really confused why it triggered the error. It looks like WP_Query class has some methods that may check for user etc but those methods may return null because piklist somehow load my plugin very early, or something like that, it is just my guess. 

Piklist Version:1.03

PHP Version: 7.2.8

Server OS: Apache

### What was expected to happen
I expected to receive the query result of WP_Query. 

### What happened instead
I received a fatal error like below
     `[07-Mar-2019 12:51:13 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /Applications/MAMP/htdocs/themexdev/wp-includes/query.php:28
Stack trace:
    #0 /Applications/MAMP/htdocs/themexdev/wp-content/plugins/piklist/includes/class-piklist-wordpress.php(610): get_query_var('taxonomy_relati...')
    #1 /Applications/MAMP/htdocs/themexdev/wp-includes/class-wp-hook.php(288): Piklist_WordPress::relation_taxonomy(' AND ( \n  ( wp_...')
    #2 /Applications/MAMP/htdocs/themexdev/wp-includes/plugin.php(251): WP_Hook->apply_filters(' AND ( \n  ( wp_...', Array)
    #3 /Applications/MAMP/htdocs/themexdev/wp-includes/class-wp-query.php(2519):  apply_filters_ref_array('posts_where', Array)
    #4 /Applications/MAMP/htdocs/themexdev/wp-includes/class-wp-query.php(3387): WP_Query->get_posts()
    #5 /Applications/MAMP/htdocs/themexdev/wp-includes/class-wp-query.php(3496): WP_Query->query(Array)
    #6 /Applications/MAMP/htdocs/themexdev/wp-content/plugins/xlaw-core/includes/xlaw-core-helper.php(16): WP_Query->__construct(Array)
    #7 /Applications/MAMP/htdocs/themexd in /Applications/MAMP/htdocs/themexdev/wp-includes/query.php on line 28`

### Steps to reproduce this
1. Provide piklist support in your plugin header file using  * Plugin Type:       Piklist

Then Run any WP_Query() in your main plugin file or put the following query in your main plugin file and try to log the result by calling the 'xlaw_get_elementor_tmpl_lists ' function. You will get fatal error. If you disable piklist, then the following code will not generate any error.

    `if ( !function_exists( 'xlaw_get_elementor_tmpl_lists') )
    {
	/**
	 * It fetches all saved elementor templates and return it in an array
	 * @return array
	 */
	function xlaw_get_elementor_tmpl_lists() {
		if ( ! did_action( 'elementor/loaded' ) ) {
			return [''=> 'Elementor has been not loaded'];
		}
		$templates_query = new WP_Query(
			[
				'post_type' => 'elementor_library',
				'post_status' => 'publish',
				'posts_per_page' => -1,
				'orderby' => 'title',
				'order' => 'ASC',
				'meta_query' => [
					[
						'key' => '_elementor_template_type',
						'value' => ['page', 'single'], // we can also use section, widget, header, footer etc.
					],
				],
			]
		);
		$templates = [];
		if ( $templates_query->have_posts() ) {
			$templates = [ '0' => __( 'Default Template', 'xlaw-core' ) ];
			foreach ( $templates_query->get_posts() as $p ) {
				/** @var WP_Post $p*/
				$templates[$p->ID] = $p->post_title;
			}
		}
		return $templates;
	}
    }`

**Comment by dhavalgshah** [comment]
This is because `Piklist_WordPress::relation_taxonomy` uses `get_query_var()` which in turn uses `global $wp_query` internally.

Using `WP_Query` object passed in the hook would mitigate the issue as this corresponds directly to the query where we have hooked.

@kamalahmed  Can you use the patch in #126 and check if works now?
